FROM jupyterlab:latest

USER jovyan

COPY ./git_config /home/jovyan/.gitconfig
COPY ./git_credentials /home/jovyan/.git-credentials

WORKDIR /home/jovyan
RUN git config --global credential.helper store
RUN git clone https://github.com/marcocesari/playground.git
